apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
        - name: my-spring-boot-app
          image: namespace/repository-name:tag  # Docker Hub 사용자 이름을 포함한 이미지 경로
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: private-docker-hub  # Docker 인증 정보를 참조하는 Secret 이름

---

apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: my-spring-boot-app
